# Metadata for your course

title: Implementing a logging strategy # a name for your Learning Lab course
tagline: Implementing a logging strategy # a short description for your Learning Lab course, displayed on the course catalog
description: Implementing a logging strategy # a longer description for your Learning Lab course, displayed on the course's landing page

# Repository setup
# The following section template information for the repository
# This will be used when the repository is crated for each individual learner

template:
  name: my-sparkles-repo
  repo: lab-starter-template

# `before` block
# Actions to take place after the learner registers, but before they start interacting with their repo

before:
- type: createIssue
  title: Welcome
  body: welcome-text.md

# Steps for the course
# A list of steps that take the learner through the course
# Create one step for each action that a learner will complete

steps:
- title: Create a new pull request
  description: Add your name to the README.md file in your new pull request
  event: pull_request.opened
  actions:
  - type: gate
    left: '%payload.pull_request.title%'
    operator: ===
    right: Add name to README
  - type: respond
    with: pr-opened.md
  #
  # - type:
  #   option:
